name: Pipeline
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: macos-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Test
        run: deno task test

      - name: Format
        run: deno task format

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5

      - name: Publish package
        run: deno publish
